services:

  enso-ml:
    image: dogen/enso-ml:latest
    environment:
      - HF_HOME=/enso-ml/data
    env_file:
      - ./.env
    ports:
      - "80:80"
    command: >
      bash -c "true \
      && sleep infinity
      && (cargo build --release)
      && (./ml-worker & ./enso-ml)
      "
    volumes:
      - ./data:/enso-ml/data
      - ./media:/enso-ml/media
      - ./src:/enso-ml/src
      - ./Cargo.toml:/enso-ml/Cargo.toml
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    expose:
      - "6379"

networks:
  default:
