services:

  enso-ml:
    image: dogen/enso-ml:latest
    environment:
      - HF_HOME=/enso-ml/data
    env_file:
      - ./.env
    ports:
      - "80:80"
    command: >
      bash -c "true \
      && (cargo build --release)
      && (./ml-worker & ./enso-ml)
      && sleep infinity
      "
    volumes:
      - ./data:/enso-ml/data
      - ./media:/enso-ml/media
      - ./src:/enso-ml/src
      - ./gui:/enso-ml/gui
      - ./Cargo.toml:/enso-ml/Cargo.toml
      - cargo_cache:/root/.cargo
      - target_cache:/enso-ml/target
    depends_on:
      - redis
      - minio
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    expose:
      - "6379"

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - default

volumes:
  minio_data:
  cargo_cache:
  target_cache:

networks:
  default:
